### ISSUE TITLE
Warning message shown in `ember-try` scenarios

### ISSUE THREAD

**Issue by Turbo87** [ember-polyfills/ember-getowner-polyfill#16]
I'm seeing

```
ember-getowner-polyfill is not required for Ember 2.3.0 and later,
please remove from your `package.json`.
```

when testing some addons via `ember-try`. These addons are compatible down to v1.13/2.0 which obviously requires the polyfill, but it is still warning when we test against more recent releases. Is there some way to disable the warning?

**Comment by rwjblue** [comment]
Nope, it should warn if used with a newer Ember version. This seems totally fine, and only a minor inconvenience.

**Comment by Turbo87** [comment]
I'm not sure I agree. Should all polyfills warn if used in newer environments where they're deactivated automatically? that seems a little strange.

**Comment by rwjblue** [comment]
The warning is primarily for apps, and yes you should absolutely remove `ember-getowner-polyfill` from your application if you are using Ember 2.3+.  

When an addon depends on `ember-getowner-polyfill` this warning is not shown to consumers of the addon (even if they are using Ember 2.3+).  [See this guard ](https://github.com/rwjblue/ember-getowner-polyfill/blob/5c6963462494280654bec804b5543eb41e2bbf31/index.js#L17) for how we prevent warnings in that scenario. This is simply a minor minor annoyance while developing the addon itself, and you can always use `ember-try` to remove the polyfill if it bothers you a bunch.

**Comment by Turbo87** [comment]
@rwjblue example of how this warning can be confusing: https://github.com/simplabs/ember-simple-auth/pull/1124#discussion_r91711525

**Comment by Turbo87** [comment]
@rwjblue another one https://github.com/simplabs/ember-simple-auth/pull/1190#discussion_r98632477 😉

**Comment by rwjblue** [comment]
Going to close for now (so I can archive the repo), I do think we should generally find a better way to message this in polyfills.
