### ISSUE TITLE
DEPRECATION: An addon is trying to access project.nodeModulesPath.

### ISSUE THREAD

**Issue by rinoldsimon** [ember-polyfills/ember-getowner-polyfill#29]
The following deprecation is thrown on a new Ember 2.18.0 Version when starting the server. It seems some package needs to be updated.

This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   new NPMDependencyVersionChecker (/Users/rinoldsimon/mbproject/medzbook_client/node_modules/ember-getowner-polyfill/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:33)

**Comment by rwjblue** [comment]
This is landed....
