### ISSUE TITLE
DEPRECATION: ember-cli-babel 5.x has been deprecated

### ISSUE THREAD

**Issue by rinoldsimon** [ember-polyfills/ember-getowner-polyfill#30]
After installing ember-getowner-polyfill in an Ember project, following error appears when running the server:

> DEPRECATION:ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6.0

### Environment
Ember Version: 2.18.2
Ember CLI Version: 2.18.2
### Steps to Reproduce
In the Ember project install ember-getowner-polyfill:

> ember install ember-getowner-polyfill

After that run an Ember command like:

> ember -v

or:

> ember s

**Comment by rinoldsimon** [comment]
`ember-getowner-polyfill` is still using `ember-cli-babel 5.x`. update `ember-cli-babel` to 6.6.0 or above

**Comment by rwjblue** [comment]
Thanks for reporting! We should move ember-cli-babel to devDependencies (we have no code that requires build time transpilation)...

**Comment by rinoldsimon** [comment]
when will this issue be fixed ?

**Comment by jbrz** [comment]
someone clarify for me - package.json shows babel at 6.6+ and it's under devDependencies, so...what's the issue here?

**Comment by rwjblue** [comment]
Fixed by #32
